require("ui.uieditor.widgets.EndGameFlow.Top3PlayerScoreBlurBox")
require("ui.uieditor.widgets.Lobby.Common.FE_ButtonPanel")
require("ui.uieditor.widgets.HelperWidgets.TextWithBg")
require("ui.uieditor.widgets.Scoreboard.scoreboardPingBackground")
require("ui.uieditor.widgets.Lobby.Common.FE_FocusBarContainer")
local f0_local0 = function (f1_arg0, f1_arg1, f1_arg2)
	f1_arg0:subscribeToModel(Engine.GetModel(Engine.GetModelForController(f1_arg1), "factions.isCoDCaster"), function (ModelRef)
		local f3_local0 = f1_arg0:getModel(f1_arg1, "team")
		if f3_local0 then
			Engine.ForceNotifyModelSubscriptions(f3_local0)
		end
	end)
end

CoD.ScoreboardRowWidget = InheritFrom(LUI.UIElement)
CoD.ScoreboardRowWidget.new = function (HudRef, InstanceRef)
	local Widget = LUI.UIElement.new()
	if PreLoadFunc then
		PreLoadFunc(Widget, InstanceRef)
	end
	Widget:setUseStencil(false)
	Widget:setClass(CoD.ScoreboardRowWidget)
	Widget.id = "ScoreboardRowWidget"
	Widget.soundSet = "default"
	Widget:setLeftRight(true, false, 0, 853)
	Widget:setTopBottom(true, false, 0, 25)
	--Widget:makeFocusable()
	--Widget:setHandleMouse(true)
	Widget.anyChildUsesUpdateState = true
	local f2_local1 = LUI.UIImage.new()
	f2_local1:setLeftRight(true, true, 0, -60)
	f2_local1:setTopBottom(true, true, 0, 0)
	f2_local1:setRGB(0, 0, 0)
	f2_local1:setAlpha(0)
	Widget:addElement(f2_local1)
	Widget.BlackBar = f2_local1
	
	local f2_local2 = CoD.Top3PlayerScoreBlurBox.new(HudRef, InstanceRef)
	f2_local2:setLeftRight(true, true, 0, -60)
	f2_local2:setTopBottom(true, true, 0, 0)
	f2_local2:setRFTMaterial(LUI.UIImage.GetCachedMaterial("uie_scene_blur_pass_2"))
	f2_local2:setShaderVector(0, 10, 10, 0, 0)
	--Widget:addElement(f2_local2)
	Widget.Top3PlayerScoreBlurBox0 = f2_local2

    local blood = LUI.UIImage.new()
	blood:setLeftRight(true, true, 48, 0)
	blood:setTopBottom(true, true, 0, 0)
	blood:setImage(RegisterImage("score_blood1_lg" ))
    blood:setRGB(0.4, 0.055, 0.078)
    blood:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue and ModelValue >= 0 then
            local index = ModelValue + 1
			blood:setImage(RegisterImage("score_blood" .. index .. "_lg"))
        else
            blood:setAlpha(0)
		end
	end)
	Widget:addElement(blood)
	Widget.Blood = blood
	
	local f2_local3 = CoD.FE_ButtonPanel.new(HudRef, InstanceRef)
	f2_local3:setLeftRight(true, true, 0, -60)
	f2_local3:setTopBottom(true, true, 0, 0)
	f2_local3:setRGB(0, 0, 0)
	f2_local3:setAlpha(0.45)
	--Widget:addElement(f2_local3)
	Widget.VSpanel = f2_local3
	
	local f2_local4 = LUI.UIText.new()
	f2_local4:setLeftRight(true, false, 23, 52)
	f2_local4:setTopBottom(false, false, -10.5, 11.5)
	f2_local4:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local4:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_CENTER)
	f2_local4:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_TOP)
	f2_local4:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local4:setRGB(SetToParagonColorIfPrestigeMasterForScoreboard(InstanceRef, 255, 255, 255, ModelValue))
		end
	end)
	f2_local4:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local4:setText(Engine.Localize(GetScoreboardPlayerRank(InstanceRef, ModelValue)))
		end
	end)
	--Widget:addElement(f2_local4)
	Widget.Rank = f2_local4
	
	local f2_local5 = LUI.UIImage.new()
	f2_local5:setLeftRight(true, false, 52, 76)
	f2_local5:setTopBottom(false, false, -12, 12)
	f2_local5:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local5:setImage(RegisterImage(GetScoreboardPlayerRankIcon(InstanceRef, ModelValue)))
		end
	end)
	--Widget:addElement(f2_local5)
	Widget.RankIcon = f2_local5
	
	local f2_local6 = LUI.UIText.new()
	f2_local6:setLeftRight(true, false, 82, 335)
	f2_local6:setTopBottom(false, false, 0, 6)
	f2_local6:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local6:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_LEFT)
	f2_local6:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_TOP)
	f2_local6:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
            f2_local6:setRGB(ZombieClientScoreboardColor(ModelValue))
			f2_local6:setText(GetClientName(InstanceRef, ModelValue))
		end
	end)
	Widget:addElement(f2_local6)
	Widget.Gamertag = f2_local6
	
	local f2_local7 = CoD.TextWithBg.new(HudRef, InstanceRef)
	f2_local7:setLeftRight(false, true, -493.09, -406.09)
	f2_local7:setTopBottom(true, true, 0, 0)
	f2_local7.Bg:setAlpha(0)
	f2_local7.Text:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local7.Text:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_CENTER)
	f2_local7:linkToElementModel(Widget, "team", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local7.Bg:setRGB(GetScoreboardTeamBackgroundColor(InstanceRef, ModelValue))
		end
	end)
	f2_local7:linkToElementModel(Widget, "clientNumScoreInfoUpdated", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local7.Text:setText(Engine.Localize(GetScoreboardPlayerScoreColumn(InstanceRef, 0, ModelValue)))
		end
	end)
    f2_local7:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
            f2_local7.Text:setRGB(ZombieClientScoreboardColor(ModelValue))
		end
	end)
	Widget:addElement(f2_local7)
	Widget.ScoreColumn1 = f2_local7
	
	local f2_local8 = CoD.TextWithBg.new(HudRef, InstanceRef)
	f2_local8:setLeftRight(false, true, -406.09, -319.09)
	f2_local8:setTopBottom(true, true, 0, 0)
	f2_local8.Bg:setRGB(0.3, 0.27, 0.27)
	f2_local8.Bg:setAlpha(0)
	f2_local8.Text:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local8.Text:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_CENTER)
	f2_local8:linkToElementModel(Widget, "clientNumScoreInfoUpdated", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local8.Text:setText(Engine.Localize(GetScoreboardPlayerScoreColumn(InstanceRef, 1, ModelValue)))
		end
	end)
    f2_local8:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
            f2_local8.Text:setRGB(ZombieClientScoreboardColor(ModelValue))
		end
	end)
	Widget:addElement(f2_local8)
	Widget.ScoreColumn2 = f2_local8
	
	local f2_local9 = CoD.TextWithBg.new(HudRef, InstanceRef)
	f2_local9:setLeftRight(false, true, -319.09, -232.09)
	f2_local9:setTopBottom(true, true, 0, 0)
	f2_local9.Bg:setAlpha(0)
	f2_local9.Text:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local9.Text:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_CENTER)
	f2_local9:linkToElementModel(Widget, "team", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local9.Bg:setRGB(GetScoreboardTeamBackgroundColor(InstanceRef, ModelValue))
		end
	end)
	f2_local9:linkToElementModel(Widget, "clientNumScoreInfoUpdated", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local9.Text:setText(Engine.Localize(GetScoreboardPlayerScoreColumn(InstanceRef, 2, ModelValue)))
		end
	end)
    f2_local9:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
            f2_local9.Text:setRGB(ZombieClientScoreboardColor(ModelValue))
		end
	end)
	Widget:addElement(f2_local9)
	Widget.ScoreColumn3 = f2_local9
	
	local f2_local10 = CoD.TextWithBg.new(HudRef, InstanceRef)
	f2_local10:setLeftRight(false, true, -232.09, -145.09)
	f2_local10:setTopBottom(true, true, 0, 0)
	f2_local10.Bg:setRGB(0.3, 0.27, 0.27)
	f2_local10.Bg:setAlpha(0)
	f2_local10.Text:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local10.Text:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_CENTER)
	f2_local10:linkToElementModel(Widget, "clientNumScoreInfoUpdated", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local10.Text:setText(Engine.Localize(GetScoreboardPlayerScoreColumn(InstanceRef, 3, ModelValue)))
		end
	end)
    f2_local10:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
            f2_local10.Text:setRGB(ZombieClientScoreboardColor(ModelValue))
		end
	end)
	Widget:addElement(f2_local10)
	Widget.ScoreColumn4 = f2_local10
	
	local f2_local11 = CoD.TextWithBg.new(HudRef, InstanceRef)
	f2_local11:setLeftRight(false, true, -145.09, -62.09)
	f2_local11:setTopBottom(true, true, 0, 0)
	f2_local11.Bg:setAlpha(0)
	f2_local11.Text:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local11.Text:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_CENTER)
	f2_local11:linkToElementModel(Widget, "team", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local11.Bg:setRGB(GetScoreboardTeamBackgroundColor(InstanceRef, ModelValue))
		end
	end)
	f2_local11:linkToElementModel(Widget, "clientNumScoreInfoUpdated", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local11.Text:setText(Engine.Localize(GetScoreboardPlayerScoreColumn(InstanceRef, 4, ModelValue)))
		end
	end)
    f2_local11:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
            f2_local11.Text:setRGB(ZombieClientScoreboardColor(ModelValue))
		end
	end)
	Widget:addElement(f2_local11)
	Widget.ScoreColumn5 = f2_local11
	
	local f2_local12 = LUI.UIImage.new()
	f2_local12:setLeftRight(false, true, -60, -24)
	f2_local12:setTopBottom(true, true, 0, 0)
	f2_local12:setRGB(0.35, 0.3, 0.3)
	f2_local12:setAlpha(GetScoreboardPingValueAlpha(0.5))
	--Widget:addElement(f2_local12)
	Widget.pvBackground = f2_local12
	
	local f2_local13 = CoD.scoreboardPingBackground.new(HudRef, InstanceRef)
	f2_local13:setLeftRight(true, false, 793, 829)
	f2_local13:setTopBottom(true, false, 0, 25)
	f2_local13:linkToElementModel(Widget, "ping", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local13:setAlpha(GetScoreboardPingBarAlpha(ModelValue))
		end
	end)
	f2_local13:linkToElementModel(Widget, nil, false, function (ModelRef)
		f2_local13:setModel(ModelRef, InstanceRef)
	end)
	--Widget:addElement(f2_local13)
	Widget.scoreboardPingBackground = f2_local13
	
	local f2_local14 = LUI.UIText.new()
	f2_local14:setLeftRight(false, true, -60, -28)
	f2_local14:setTopBottom(false, false, -11, 11)
	f2_local14:setAlpha(GetScoreboardPingValueAlpha(1))
	f2_local14:setTTF("fonts/RefrigeratorDeluxe-Regular.ttf")
	f2_local14:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_RIGHT)
	f2_local14:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_TOP)
	f2_local14:linkToElementModel(Widget, "ping", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local14:setText(ModelValue)
		end
	end)
    f2_local14:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue and ModelValue >= 0 then
            f2_local14:setRGB(ZombieClientScoreboardColor(ModelValue))
            f2_local14:setAlpha(GetScoreboardPingValueAlpha(1))
        else
            f2_local14:setAlpha(0)
        end
	end)
	Widget:addElement(f2_local14)
	Widget.PingText = f2_local14
	
	local f2_local15 = LUI.UIImage.new()
	f2_local15:setLeftRight(true, false, 342, 363)
	f2_local15:setTopBottom(true, false, 2.5, 23.5)
	f2_local15:setAlpha(0)
	f2_local15:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local15:setupVoipImage(ModelValue)
		end
	end)
	--Widget:addElement(f2_local15)
	Widget.VOIPImage = f2_local15
	
	local f2_local16 = LUI.UIImage.new()
	f2_local16:setLeftRight(true, false, 0, 23)
	f2_local16:setTopBottom(true, false, 1, 24)
	f2_local16:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		local ModelValue = Engine.GetModelValue(ModelRef)
		if ModelValue then
			f2_local16:setupClientStatusImage(ModelValue)
		end
	end)
	Widget:addElement(f2_local16)
	Widget.ScoreboardRowDeathIcon = f2_local16
	
	local f2_local17 = CoD.FE_FocusBarContainer.new(HudRef, InstanceRef)
	f2_local17:setLeftRight(true, true, 0, -60)
	f2_local17:setTopBottom(false, true, -2, 2)
	f2_local17:setAlpha(0)
	f2_local17:setZoom(1)
	--Widget:addElement(f2_local17)
	Widget.FocusBarB = f2_local17
	
	local f2_local18 = CoD.FE_FocusBarContainer.new(HudRef, InstanceRef)
	f2_local18:setLeftRight(true, true, 0, -60)
	f2_local18:setTopBottom(true, false, -2, 2)
	f2_local18:setAlpha(0)
	f2_local18:setZoom(1)
	--Widget:addElement(f2_local18)
	Widget.FocusBarT = f2_local18
	
	Widget.clipsPerState = {DefaultState = {DefaultClip = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(1)
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.Rank:setLeftRight(true, false, 23, 52)
		Widget.Rank:setTopBottom(false, false, -11, 10)
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		Widget.Gamertag:setLeftRight(true, false, 82, 335)
		Widget.Gamertag:setTopBottom(false, false, -12, 10)
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end, Focus = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(1)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(1)
		Widget.clipFinished(f2_local18, {})
	end}, GenesisEndGame = {DefaultClip = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(0)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(0)
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.Rank:setLeftRight(true, false, 23, 52)
		Widget.Rank:setTopBottom(false, false, -11, 10)
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		Widget.Gamertag:setLeftRight(true, false, 82, 335)
		Widget.Gamertag:setTopBottom(false, false, -12, 10)
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end, Focus = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(0)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(0)
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(1)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(1)
		Widget.clipFinished(f2_local18, {})
	end}, IsCoDCaster = {DefaultClip = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(1)
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.Rank:setLeftRight(true, false, 23, 52)
		Widget.Rank:setTopBottom(false, false, -11, 10)
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		Widget.Gamertag:setLeftRight(true, false, 82, 335)
		Widget.Gamertag:setTopBottom(false, false, -12, 10)
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(0)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		--Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(0)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		--Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(0)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(0)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(0)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end}, FrontendArabic = {DefaultClip = function ()
		Widget:setupElementClipCounter(11)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(1)
        Widget.clipFinished(blood, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.Gamertag:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_RIGHT)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end}, Frontend = {DefaultClip = function ()
		Widget:setupElementClipCounter(11)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(1)
        Widget.clipFinished(blood, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end}, IsSelfArabic = {DefaultClip = function ()
		Widget:setupElementClipCounter(11)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.Blood:setAlpha(1)
        Widget.clipFinished(blood, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 0.84, 0.04)
		Widget.Gamertag:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_RIGHT)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end, Focus = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 0.84, 0.04)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		--Widget.ScoreColumn1.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		--Widget.ScoreColumn2.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		--Widget.ScoreColumn3.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		--Widget.ScoreColumn4.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		--Widget.ScoreColumn5.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(1)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(1)
		Widget.clipFinished(f2_local18, {})
	end}, IsSelf = {DefaultClip = function ()
		Widget:setupElementClipCounter(11)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.Top3PlayerScoreBlurBox0:setAlpha(1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.clipFinished(blood, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 0.84, 0.04)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end, Focus = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 0.84, 0.04)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		--Widget.ScoreColumn1.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		--Widget.ScoreColumn2.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		--Widget.ScoreColumn3.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		--Widget.ScoreColumn4.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		--Widget.ScoreColumn5.Text:setRGB(1, 0.84, 0.04)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(1)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(1)
		Widget.clipFinished(f2_local18, {})
	end}, DefaultStateArabic = {DefaultClip = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.Rank:setLeftRight(true, false, 23, 52)
		Widget.Rank:setTopBottom(false, false, -11, 10)
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		Widget.Gamertag:setLeftRight(true, false, 82, 335)
		Widget.Gamertag:setTopBottom(false, false, -12, 10)
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.Gamertag:setAlignment(Enum.LUIAlignment.LUI_ALIGNMENT_RIGHT)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		Widget.ScoreColumn1:setAlpha(1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		Widget.ScoreColumn2:setAlpha(1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		Widget.ScoreColumn3:setAlpha(1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		Widget.ScoreColumn4:setAlpha(1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		Widget.ScoreColumn5:setAlpha(1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(0)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(0)
		Widget.clipFinished(f2_local18, {})
	end, Focus = function ()
		Widget:setupElementClipCounter(12)
		f2_local2:completeAnimation()
		Widget.Top3PlayerScoreBlurBox0:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local2, {})
        blood:completeAnimation()
        Widget.clipFinished(blood, {})
		f2_local4:completeAnimation()
		Widget.clipFinished(f2_local4, {})
		f2_local5:completeAnimation()
		Widget.RankIcon:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local5, {})
		f2_local6:completeAnimation()
		--Widget.Gamertag:setRGB(1, 1, 1)
		Widget.clipFinished(f2_local6, {})
		f2_local7:completeAnimation()
		f2_local7.Text:completeAnimation()
		Widget.ScoreColumn1:setRGB(1, 1, 1)
		--Widget.ScoreColumn1.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn1.Text:setAlpha(1)
		Widget.clipFinished(f2_local7, {})
		f2_local8:completeAnimation()
		f2_local8.Text:completeAnimation()
		Widget.ScoreColumn2:setRGB(1, 1, 1)
		--Widget.ScoreColumn2.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn2.Text:setAlpha(1)
		Widget.clipFinished(f2_local8, {})
		f2_local9:completeAnimation()
		f2_local9.Text:completeAnimation()
		Widget.ScoreColumn3:setRGB(1, 1, 1)
		--Widget.ScoreColumn3.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn3.Text:setAlpha(1)
		Widget.clipFinished(f2_local9, {})
		f2_local10:completeAnimation()
		f2_local10.Text:completeAnimation()
		Widget.ScoreColumn4:setRGB(1, 1, 1)
		--Widget.ScoreColumn4.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn4.Text:setAlpha(1)
		Widget.clipFinished(f2_local10, {})
		f2_local11:completeAnimation()
		f2_local11.Text:completeAnimation()
		Widget.ScoreColumn5:setRGB(1, 1, 1)
		--Widget.ScoreColumn5.Text:setRGB(1, 1, 1)
		Widget.ScoreColumn5.Text:setAlpha(1)
		Widget.clipFinished(f2_local11, {})
		f2_local17:completeAnimation()
		Widget.FocusBarB:setAlpha(1)
		Widget.clipFinished(f2_local17, {})
		f2_local18:completeAnimation()
		Widget.FocusBarT:setAlpha(1)
		Widget.clipFinished(f2_local18, {})
	end}}
	Widget:mergeStateConditions({{stateName = "GenesisEndGame", condition = function (HudRef, ItemRef, UpdateTable)
		local f34_local0 = Engine.IsVisibilityBitSet(InstanceRef, Enum.UIVisibilityBit.BIT_GAME_ENDED)
		if f34_local0 then
			f34_local0 = IsMapName("zm_genesis")
			if f34_local0 then
				f34_local0 = IsGenesisEECompleted(InstanceRef)
			end
		end
		return f34_local0
	end}, {stateName = "IsCoDCaster", condition = function (HudRef, ItemRef, UpdateTable)
		return IsScoreboardPlayerCodCaster(InstanceRef, ItemRef)
	end}, {stateName = "FrontendArabic", condition = function (HudRef, ItemRef, UpdateTable)
		local f36_local0
		if not IsInGame() then
			f36_local0 = IsCurrentLanguageArabic()
		else
			f36_local0 = false
		end
		return f36_local0
	end}, {stateName = "Frontend", condition = function (HudRef, ItemRef, UpdateTable)
		local f37_local0
		if not IsInGame() then
			f37_local0 = not IsCurrentLanguageArabic()
		else
			f37_local0 = false
		end
		return f37_local0
	end}, {stateName = "IsSelfArabic", condition = function (HudRef, ItemRef, UpdateTable)
		local f38_local0 = IsScoreboardPlayerSelf(ItemRef, InstanceRef)
		if f38_local0 then
			f38_local0 = IsCurrentLanguageArabic()
		end
		return f38_local0
	end}, {stateName = "IsSelf", condition = function (HudRef, ItemRef, UpdateTable)
		local f39_local0 = IsScoreboardPlayerSelf(ItemRef, InstanceRef)
		if f39_local0 then
			f39_local0 = not IsCurrentLanguageArabic()
		end
		return f39_local0
	end}, {stateName = "DefaultStateArabic", condition = function (HudRef, ItemRef, UpdateTable)
		return IsCurrentLanguageArabic()
	end}})
	Widget:subscribeToModel(Engine.GetModel(Engine.GetModelForController(InstanceRef), "UIVisibilityBit." .. Enum.UIVisibilityBit.BIT_GAME_ENDED), function (ModelRef)
		HudRef:updateElementState(Widget, {name = "model_validation", menu = HudRef, modelValue = Engine.GetModelValue(ModelRef), modelName = "UIVisibilityBit." .. Enum.UIVisibilityBit.BIT_GAME_ENDED})
	end)
	Widget:linkToElementModel(Widget, "clientNum", true, function (ModelRef)
		HudRef:updateElementState(Widget, {name = "model_validation", menu = HudRef, modelValue = Engine.GetModelValue(ModelRef), modelName = "clientNum"})
	end)
	Widget:subscribeToModel(Engine.GetModel(Engine.GetModelForController(InstanceRef), "deadSpectator.playerIndex"), function (ModelRef)
		HudRef:updateElementState(Widget, {name = "model_validation", menu = HudRef, modelValue = Engine.GetModelValue(ModelRef), modelName = "deadSpectator.playerIndex"})
	end)
	f2_local13.id = "scoreboardPingBackground"
	Widget:registerEventHandler("gain_focus", function (Sender, Event)
		if Sender.m_focusable then
			local f44_local0 = Sender.scoreboardPingBackground
			if f44_local0:processEvent(Event) then
				return true
			end
		end
		return LUI.UIElement.gainFocus(Sender, Event)
	end)
	LUI.OverrideFunction_CallOriginalSecond(Widget, "close", function (Sender)
		Sender.Top3PlayerScoreBlurBox0:close()
		Sender.VSpanel:close()
		Sender.ScoreColumn1:close()
		Sender.ScoreColumn2:close()
		Sender.ScoreColumn3:close()
		Sender.ScoreColumn4:close()
		Sender.ScoreColumn5:close()
		Sender.scoreboardPingBackground:close()
		Sender.FocusBarB:close()
		Sender.FocusBarT:close()
		Sender.Rank:close()
		Sender.RankIcon:close()
		Sender.Gamertag:close()
		Sender.PingText:close()
		Sender.VOIPImage:close()
		Sender.ScoreboardRowDeathIcon:close()
	end)
	if f0_local0 then
		f0_local0(Widget, InstanceRef, HudRef)
	end
	return Widget
end

