#define PANZERWURFMINE_COST_BASE 500
#define PANZERWURFMINE_COST_MAX 128000
#define PANZERWURFMINE_COST_MULT 2
#define PANZERWURFMINE_COST_SCALE_ROUNDS 10
#define PANZERWURFMINE_COOLDOWN 120
#define PANZERWURFMINE_UPGRADE_MAX_ZOMBIES 12
#define PANZERWURFMINE_UPGRADE_RADIUS 150

#define PANZERWURFMINE_UPGRADE_KILLS 25
#define MONKEY_UPGRADE_KILLS 20
#define HEALING_UPGRADE_KILLS 50

#define CROSSBOW_MAX_TIME 30
#define CROSSBOW_RECHARGE_KILLS_BASE -5 // increment will be added right away, so this means the base recharge is 5 kills
#define CROSSBOW_RECHARGE_KILLS_MULT_MIN 0.75
#define CROSSBOW_RECHARGE_KILLS_INCREMENT 10

#define NUM_ARMORY_STATIONS 5

#define NUM_TARGETS 3
#define TARGET_WAIT 4
#define PUZZLE_FAIL_WAIT 1.5

#define TARGET_SEQUENCE_INACTIVE 0
#define TARGET_SEQUENCE_OTHER 1
#define TARGET_SEQUENCE_SAME 2

#define SYMBOL_LOOKAT_DOT 0.99